### PR TITLE
Remove ATFWD-daemon binary file and add a function called add_file_to_obj_lib

### PR DESCRIPTION
**Pull request by marcofreda527**
1. Remove ATFWD-daemon because that file will hang up the system on ICS_Strawberry version.
2. Add new function for adding files into out/target/product/XXX/obj/lib which will be used to check dependency during compile time.

### CODE REVIEW

**Comment by michaelwu** [comment]
Removal of files should generally be avoided since it's not an accurate representation of what vendor/production builds would look like. We should also get the vendor to disable this.

**Comment by michaelwu** [comment]
Which parts of the tree look for libcnefeatureconfig.so ? I remember seeing this in strawberry but I didn't investigate it too deeply.

**Comment by marcofreda527** [comment]
1. ATFWD-daemon didn't be appeared on partner's newest images (V104).
2. frameworks/base/core/jni/android_hardware_fm.cpp

**Comment by michaelwu** [comment]
I wonder if we could copy every .so to obj/lib so we don't have to explicitly add libcnefeatureconfig.so.

**Comment by marcofreda527** [comment]
1. Follow up the comments for coding style and naming convention.
2. I still keep to mark necessary files into obj/lib.
   Because for some debugging or development process, we may need to push original blobs into device.

**Comment by michaelwu** [comment]
On second thought, this solution for libcnefeatureconfig.so seems overengineered.

Let's just do:
 echo $BASE_PROPRIETARY_COMMON_DIR/libcnefeatureconfig.so:obj/lib/libcnefeatureconfig.so \ >> $COMMON_BLOBS_LIST

No need to add an extra function to do this when there's no evidence we'll need to reuse this in the future.

**Comment by marcofreda527** [comment]
Hi Michael,

Any comment for this? thanks.

**Comment by marcofreda527** [comment]
Hamachi is closed.

**Pull request closed without merging**
